### ISSUE TITLE
Make program to run configurable

### ISSUE THREAD

**Issue by nomeata** [Genetic-Strictness/Autobahn#6]
Many projects define multiple executables, some of which are not named the same way as the project. It would be good if that were configurable.

**Comment by cronburg** [comment]
This is a result of how the `runProj` system call string is constructed in the `benchmark` function of `Profiling.hs`. Namely `projDir` is referenced when we should presumably be referencing the list of executable files given in the `config.atb` file.

**Comment by cronburg** [comment]
Implemented in 45909f404e9b8a31cc827aca606e2a11a6c5175d - see [`test/hello/config.atb`](https://github.com/Genetic-Strictness/Autobahn/blob/master/test/hello/config.atb) for example usage of the 'executable' option. 

To test multiple different executables, one still needs to create multiple `config.atb` files, which seems reasonable to me since e.g. each executable will have different input arguments and a different amount of time one might want to budget for it. We'll be adding a way to specify the name of `config.atb` on the command line soon (Issue #21).
